- name: Update APT cache
  ansible.builtin.apt:
    cache_valid_time: 3600

- name: Install Prometheus
  ansible.builtin.apt:
    name: prometheus
    state: present

- name: Install dependencies for Grafana
  ansible.builtin.apt:
    name: apt-transport-https
    state: present

- name: Add Grafana APT key
  ansible.builtin.get_url:
    url: https://packages.grafana.com/gpg.key
    dest: /usr/share/keyrings/grafana.key

- name: Add Grafana repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/grafana.key] https://packages.grafana.com/oss/deb stable main"
    state: present

- name: Install Grafana
  ansible.builtin.apt:
    name: grafana
    state: present
    update_cache: yes

- name: Enable and start Prometheus
  ansible.builtin.systemd:
    name: prometheus
    enabled: yes
    state: started

- name: Enable and start Grafana
  ansible.builtin.systemd:
    name: grafana-server
    enabled: yes
    state: started
