- name: Update apt package cache (equivalent to 'apt update')
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install required system packages (curl, openssh-server, ca-certificates, perl, locales)
  ansible.builtin.apt:
    name:
      - curl
      - openssh-server
      - ca-certificates
      - perl
      - locales
    state: present

- name: Add GitLab's GPG key (to verify package signatures)
  ansible.builtin.apt_key:
    url: "https://packages.gitlab.com/gitlab/gitlab-ce/gpgkey"
    state: present

- name: Add the GitLab CE APT repository
  ansible.builtin.apt_repository:
    repo: "deb https://packages.gitlab.com/gitlab/gitlab-ce/ubuntu {{ ansible_distribution_release }} main"
    state: present
    filename: gitlab-ce

- name: Update apt package cache (to include packages from the new repo)
  ansible.builtin.apt:
    update_cache: yes

- name: Install and initially configure GitLab CE
  ansible.builtin.apt:
    name: gitlab-ce
    state: present
  environment:
    GITLAB_ROOT_PASSWORD: "{{ gitlab_root_password }}"
    EXTERNAL_URL: "{{ gitlab_external_url }}"
    GITLAB_OMNIBUS_CONFIG: |
      letsencrypt['enable'] = false
      nginx['redirect_http_to_https'] = false
  notify:
    - Wait for GitLab to reconfigure