- name: Update apt package cache 
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install curl and ca-certificates
  ansible.builtin.apt:
    pkg:
    - curl
    - ca-certificates

- name: Create /etc/apt/keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

- name: Update apt package cache 
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install docker packages
  ansible.builtin.apt:
    name:
    - docker-ce
    - docker-ce-cli 
    - containerd.io 
    - docker-buildx-plugin
    - docker-compose-plugin
    state: present
