- name: Check Nginx configuration syntax
  ansible.builtin.shell: |
    docker compose exec -T nginx-proxy nginx -t
  register: nginx_syntax_check
  failed_when: nginx_syntax_check.rc != 0

- name: Restart Nginx container
  ansible.builtin.shell: |
    cd {{ ansible_env.HOME }}/docker-compose/
    docker compose down && docker compose up -d
