services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    network_mode: "host"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${HOME}/docker-compose/configs:/etc/nginx/conf.d/
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/html:/var/www/html
    restart: unless-stopped