services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${HOME}/docker-compose/configs:/etc/nginx/conf.d/
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: unless-stopped